/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filestore.h"
#include <string.h>
#include <strings.h>

char* getFullFilePath(char *name);

void
file_store_1(char *host,char *name)
{
	CLIENT *clnt;
	int  *result_1;
	filename  getfilesize_1_arg=name;
	filechunk  *result_2;
	request  getfilebychunks_1_arg;
	
	int pos=0, size=0;
	getfilebychunks_1_arg.name = name; getfilebychunks_1_arg.pos=0;
#ifndef	DEBUG
	clnt = clnt_create (host, FILE_STORE, FILE_STORE_VER_1, "udp");
	//clnt = clnt_create (host, FILE_STORE, FILE_STORE_VER_1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = getfilesize_1(&getfilesize_1_arg, clnt); printf("%d",*result_1);
	size = *result_1;
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	char *fullpath = getFullFilePath(name);
	FILE *fp;	
	if(size >0 ) {
	 fp = fopen(fullpath,"w+");	
	}

	while(size > 0) {
	result_2 = getfilebychunks_1(&getfilebychunks_1_arg, clnt);
		if (result_2 == (filechunk *) NULL) {
		clnt_perror (clnt, "call failed");
		}
	//printf("%s",result_2->filechunk_val);
	fputs(result_2->filechunk_val, fp);
	int bytesread=strlen(result_2->filechunk_val);
	size-=bytesread;
	pos+=bytesread;
	getfilebychunks_1_arg.pos=pos;
	}
	fclose(fp);
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

char* getFullFilePath(char *name) {
char *full_path = malloc(strlen(CLIENT_FILE_PATH)+1);
memset(full_path,'\0',strlen(CLIENT_FILE_PATH)+1);
strcpy(full_path,CLIENT_FILE_PATH);
full_path= realloc(full_path,strlen(full_path)+strlen(name));
strcat(full_path,name); printf("%s",full_path);
return full_path;
}


int
main (int argc, char *argv[])
{
	char *host, *filename;

	if (argc < 3) {
		printf ("usage: %s server_host file_name\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	filename = argv[2];
	file_store_1 (host,filename);
exit (0);
}
