/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filestore.h"

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filechunk (XDR *xdrs, filechunk *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->filechunk_val, (u_int *) &objp->filechunk_len, 1024))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request (XDR *xdrs, request *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->pos))
		 return FALSE;
	return TRUE;
}
