/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILESTORE_H_RPCGEN
#define _FILESTORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define SERVER_FILE_PATH "filestore/"
#define CLIENT_FILE_PATH "clientstore/"

typedef char *filename;

typedef struct {
	u_int filechunk_len;
	char *filechunk_val;
} filechunk;

struct request {
	filename name;
	int pos;
};
typedef struct request request;

#define FILE_STORE 0x23453333
#define FILE_STORE_VER_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETFILESIZE 1
extern  int * getfilesize_1(filename *, CLIENT *);
extern  int * getfilesize_1_svc(filename *, struct svc_req *);
#define GETFILEBYCHUNKS 2
extern  filechunk * getfilebychunks_1(request *, CLIENT *);
extern  filechunk * getfilebychunks_1_svc(request *, struct svc_req *);
extern int file_store_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETFILESIZE 1
extern  int * getfilesize_1();
extern  int * getfilesize_1_svc();
#define GETFILEBYCHUNKS 2
extern  filechunk * getfilebychunks_1();
extern  filechunk * getfilebychunks_1_svc();
extern int file_store_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_filechunk (XDR *, filechunk*);
extern  bool_t xdr_request (XDR *, request*);

#else /* K&R C */
extern bool_t xdr_filename ();
extern bool_t xdr_filechunk ();
extern bool_t xdr_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILESTORE_H_RPCGEN */
