/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "filestore.h"
#include <string.h>
#include <strings.h>

int getFileSize(char* name);
char* getFullFilePath(char *name);
char* getFileByChunks(char* name, int pos);

int *
getfilesize_1_svc(filename *argp, struct svc_req *rqstp)
{
	static int  result=0;

	/*
	 * insert server code here
	 */
	if(argp) {
	printf("%s",*argp);
	result=	getFileSize(*argp);
	}
	printf("%d",result);

	return &result;
}

filechunk *
getfilebychunks_1_svc(request *argp, struct svc_req *rqstp)
{
	static filechunk  result;

	/*
	 * insert server code here
	 */
	result.filechunk_val = getFileByChunks(argp->name,argp->pos);
	result.filechunk_len = strlen(result.filechunk_val);

	return &result;
}

/*These are my internal function definitions*/
int getFileSize(char* name) {
int size=0;
	if(name != NULL) {
	char* full_path = getFullFilePath(name);
	FILE *fp = fopen(full_path,"r");
	fseek(fp,0,SEEK_END);
	size=ftell(fp);
	rewind(fp);
	fclose(fp);
	free(full_path);
	}
return size;
}

char* getFullFilePath(char *name) {
char *full_path = malloc(strlen(SERVER_FILE_PATH)+1);
memset(full_path,'\0',strlen(SERVER_FILE_PATH)+1);
strcpy(full_path,SERVER_FILE_PATH);
full_path= realloc(full_path,strlen(full_path)+strlen(name));
strcat(full_path,name); printf("%s",full_path);
return full_path;
}

char* getFileByChunks(char* name, int pos){
char *chunk= malloc(1024); memset(chunk,'\0',1024);
memset(chunk,'\0',1024);
char* full_path = getFullFilePath(name);
FILE *fp = fopen(full_path,"r");
if(fp==NULL){
return NULL;
}
fseek(fp,pos,SEEK_SET);
fgets(chunk,1024,fp);
fclose(fp);
return chunk;

}
